export const DEFAULT_IFX_EMAIL = "msadovyi@code.store";

export const IFX_EVENTS_GROUPED = {
	story: [
		"story:create",
		"story:create-redirect",
		"story:delete",
		"story:delete-redirect",
		"story:first-publish",
		"story:republish",
		"story:save",
		"story:unpublish",
		"story:update",
	],
	websked: [
		"websked:edition_finalize",
		"websked:pitch_create",
		"websked:publication_pitch_create",
		"websked:publication_pitch_update",
		"websked:task_assign",
		"websked:task_claim",
		"websked:task_complete",
		"websked:task_create",
		"websked:task_deadline",
		"websked:task_deadline_approaching",
	],
	author: ["author:create", "author:delete", "author:update"],
	composer: ["composer:send_to_print"],
	gallery: ["gallery:create", "gallery:delete", "gallery:publish", "gallery:save", "gallery:unpublish"],
	image: ["image:create", "image:delete", "image:update", "image:update-unpublished"],
	section: ["section:delete", "section:update"],
	site: ["site:create", "site:update"],
	url: ["url:redirect", "url:redirect-delete"],
	collection: ["collection:create", "collection:delete", "collection:publish"],
	commerce: [
		"commerce:abandoned_cart",
		"commerce:account_deletion_notification",
		"commerce:account_deletion_request_completed",
		"commerce:account_deletion_request_decision",
		"commerce:account_deletion_requested",
		"commerce:algolia_document_index_failure",
		"commerce:algolia_document_transform",
		"commerce:anonymize_user_deletion_requested",
		"commerce:authorize_payment",
		"commerce:cancel_scheduled_price_change_event",
		"commerce:cancel_subscription",
		"commerce:capture",
		"commerce:cart_add_after",
		"commerce:cart_add_before",
		"commerce:charge",
		"commerce:create_email_domain",
		"commerce:delete_email_group_sub",
		"commerce:dunning_reminder",
		"commerce:email_verified",
		"commerce:event_status_change",
		"commerce:express_checkout_password_reset_request",
		"commerce:extend_subscription",
		"commerce:fail_renew_subscription",
		"commerce:finalize_payment",
		"commerce:finalize_payment_after",
		"commerce:finalize_payment_before",
		"commerce:finalize_payment_update",
		"commerce:force_password_reset",
		"commerce:gdpr_report_ready",
		"commerce:gift_recipient_set",
		"commerce:gift_redeemed",
		"commerce:gift_subscription_purchase",
		"commerce:grant_free_subscription",
		"commerce:initialize_payment",
		"commerce:initialize_update_payment",
		"commerce:inventory_quantity_adjusted",
		"commerce:invite_to_share",
		"commerce:ip_checkout_block",
		"commerce:magic_link_send",
		"commerce:order_confirmation",
		"commerce:order_create_after",
		"commerce:order_create_before",
		"commerce:password_reset",
		"commerce:password_reset_request",
		"commerce:pending_payment",
		"commerce:pending_payment_approved",
		"commerce:pending_payment_declined",
		"commerce:price_change",
		"commerce:price_change_scheduled_event",
		"commerce:product_document_change",
		"commerce:profile_edit",
		"commerce:redeem_shared_subscription",
		"commerce:refund",
		"commerce:refund_subscription_payment",
		"commerce:renew_subscription",
		"commerce:rescue_subscription",
		"commerce:skip_subscription_payment",
		"commerce:start_subscription",
		"commerce:subscription_migration",
		"commerce:terminate_subscription",
		"commerce:upcoming_price_change_event",
		"commerce:update_billing_address",
		"commerce:update_payment_method",
		"commerce:update_sku_pricecode",
		"commerce:update_subscription_expiration_date",
		"commerce:user_sign_in_added",
		"commerce:user_sign_up",
		"commerce:user_status_updated",
		"commerce:verify_email",
		"commerce:void_authorize",
	],
};
